[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mat_discover"
authors = [{name = "Sterling G. Baird", email = "sterling.baird@utah.edu"}]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

dependencies = [
    "umap-learn",
    "tqdm",
    "seaborn",
    "pymatgen",
    "scipy",
    "hdbscan",
    "numba==0.53.1",
    "plotly",
    "kaleido",
    "pandas",
    "matplotlib",
    "joblib",
    "pqdm",
    "ElMD==0.4.3",
    "psutil",
    "PyQt5",
    "scikit_learn",
    "torch==1.7.*",
    ]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]

[project.urls]
Source = "https://github.com/sparks-baird/mat_discover"
