name: Python Package using Conda

on: 
  push:
    tags:
    - '*'

# on:
#   release:
#     types: [published]

jobs:
  flit-publish-PyPI:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install flit
      run: |
        pip install flit
    - name: Build and publish
      run: |
        flit publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
