name: Code Coverage

on: workflow_dispatch

jobs:
  linux-pytest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Upgrade pip
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install coveralls
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        export NUMBA_ENABLE_CUDASIM="1"
        coverage run --source=mat_discover -m pytest
        coveralls
